apiVersion: v1
kind: Deployment
metadata:
  name: app
  labels: 
    app: walrus-app
spec:
  replicas: 2
  template:
    metadata:
      name: app
      labels:
        app: walrus-app
    spec:
      serviceAccountName: my-serviceaccount
      containers:
      - name: app
        image: tomvogel01/app:latest
        ports:
        - containerPort: 5000
        env:
        - name: NAME
          fromValue:
            configMapKeyRef:
              name: app-config
              key: my_name
        - name: WHAT_DO_YOU_WANT
          fromValue:
            configMapKeyRef:
              name: app-config
              key: what_do_you_want
        - name: MY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: myKey
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      #   volumeMounts:
      #   - name: config-volume
      #     mountPath: /etc/config
      # volumes: 
      # - name: config-volume
      #   configMap:
      #     name: app-config

